name: Check Padle Slots

on:
  schedule:
    - cron: '*/5 7-19 * * *'  # din 04:00 până la 20:55 UTC = 10:00–23:00 RO
  workflow_dispatch:

jobs:
  check-padle:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      CALENDIS_COOKIE: ${{ secrets.CALENDIS_COOKIE }}
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
      GIST_ID: ${{ secrets.GIST_ID }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm install

      - name: Run script
        run: node padle.js
